apiVersion: v2
name: helm-nvcf-nvct-api
description: NCP Compatible deployment of NVCT API (nvct-service)

type: application
version: 0.0.0 # autoversioning enabled via release pipeline
appVersion: "1.67.0"
